name: linter

on:
  # Execute on every push to any branch
  push:
    branches:
      - "**"


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g dockerfilelint prettier@latest
      - run: dockerfilelint Dockerfile
      - run: prettier --check "**/*.md"
